
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Register extends javax.swing.JFrame {
     private Databases Account;
    /**
     * Creates new form Register
     */
    public Register() throws FileNotFoundException, IOException {
        this.Account = new Databases();
        initComponents();
        setSize(800,310);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateUser = new javax.swing.JLabel();
        createPass = new javax.swing.JLabel();
        createPass_Value = new javax.swing.JPasswordField();
        rePass_Value = new javax.swing.JPasswordField();
        CreateUser_Value = new javax.swing.JTextField();
        rePass = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        register_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        show_pass_button = new javax.swing.JCheckBox();
        incorrect_display = new javax.swing.JLabel();
        user_alreadyexist = new javax.swing.JLabel();
        Background_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CreateUser.setText("Create Username:");
        getContentPane().add(CreateUser);
        CreateUser.setBounds(230, 120, 110, 16);

        createPass.setText("Create Password:");
        getContentPane().add(createPass);
        createPass.setBounds(230, 150, 110, 16);

        createPass_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPass_ValueActionPerformed(evt);
            }
        });
        getContentPane().add(createPass_Value);
        createPass_Value.setBounds(350, 150, 130, 22);
        getContentPane().add(rePass_Value);
        rePass_Value.setBounds(350, 180, 130, 22);
        getContentPane().add(CreateUser_Value);
        CreateUser_Value.setBounds(350, 120, 130, 22);

        rePass.setText("Re-enter Password:");
        getContentPane().add(rePass);
        rePass.setBounds(230, 180, 120, 16);

        title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        title.setText("ACCOUNT REGISTERATION");
        title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(title);
        title.setBounds(230, 70, 260, 22);

        register_button.setText("Register");
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(register_button);
        register_button.setBounds(250, 220, 79, 25);

        exit_button.setText("Go back to login");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(exit_button);
        exit_button.setBounds(350, 220, 130, 25);

        show_pass_button.setText("Show password");
        show_pass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pass_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(show_pass_button);
        show_pass_button.setBounds(500, 220, 130, 25);

        incorrect_display.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        incorrect_display.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(incorrect_display);
        incorrect_display.setBounds(500, 180, 140, 20);

        user_alreadyexist.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        user_alreadyexist.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(user_alreadyexist);
        user_alreadyexist.setBounds(490, 120, 220, 20);

        Background_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AeroplaneBack.jpg"))); // NOI18N
        Background_Image.setText("jLabel1");
        getContentPane().add(Background_Image);
        Background_Image.setBounds(0, 0, 800, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO add your handling code here:
        if(rePass_Value.getText().equals(createPass_Value.getText()) && this.Account.Username_Exist(CreateUser_Value.getText()) == false)
        {
            this.Account.SaveRecord(CreateUser_Value.getText(),createPass_Value.getText() );
            
            if(this.Account.isSaveSucessful() == true)
            {
             JOptionPane.showMessageDialog(null,"Register sucess!");
             incorrect_display.setText("");
            }
            
            else
            {   JOptionPane.showMessageDialog(null,"Register unsucessful!");
                incorrect_display.setText("");
            }
            
        }
        
        else if (this.Account.Username_Exist(CreateUser_Value.getText()) == true)
        {
            user_alreadyexist.setText("This username is already taken");
        }
        
         else
        {   
            incorrect_display.setText("Incorrect password");
            JOptionPane.showMessageDialog(null,"Incorrect Password", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_register_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you want to go back to Login?","Select",JOptionPane.YES_NO_OPTION);
        
        if( a == 0) // If value evaluated zero then close the application
        {
            setVisible(false);
            try {
                new Login().setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void show_pass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pass_buttonActionPerformed
        // TODO add your handling code here:
        if(show_pass_button.isSelected())
        {
            createPass_Value.setEchoChar((char)0);
            rePass_Value.setEchoChar((char)0);
        }
        
        else
        {
           
            createPass_Value.setEchoChar('*');
            rePass_Value.setEchoChar('*');
        }
    }//GEN-LAST:event_show_pass_buttonActionPerformed

    private void createPass_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPass_ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPass_ValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Register().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_Image;
    private javax.swing.JLabel CreateUser;
    private javax.swing.JTextField CreateUser_Value;
    private javax.swing.JLabel createPass;
    private javax.swing.JPasswordField createPass_Value;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel incorrect_display;
    private javax.swing.JLabel rePass;
    private javax.swing.JPasswordField rePass_Value;
    private javax.swing.JButton register_button;
    private javax.swing.JCheckBox show_pass_button;
    private javax.swing.JLabel title;
    private javax.swing.JLabel user_alreadyexist;
    // End of variables declaration//GEN-END:variables
}
